Cypress.Commands.add("checkPageAndLogIn", ({ username, password }) => {
    cy.get('fieldset > :nth-child(1) > .ng-untouched').should('have.value', '')
    cy.get('fieldset > :nth-child(2) > .ng-untouched').should('have.value', '')
    cy.get('.background').should('be.visible')
    cy.get('#remember').should('be.checked')
    cy.get('#remember').click({ force: true })
    cy.get('#remember').should('not.be.checked')
    cy.get('.btn').click()
    cy.get('fieldset > :nth-child(1) > .text-danger').should('contain.text', 'Field is required')
    cy.get('fieldset > :nth-child(2) > .text-danger').should('contain.text', 'Field is required')
    cy.get('fieldset > :nth-child(1) > .ng-untouched').type(username)
    cy.get('fieldset > :nth-child(2) > .ng-untouched').type(password)
    cy.get('.btn').click()
})