# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run tests
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm test
    - run: npm run report
    - run: ls -la
    
    - name: Publish
      uses: appleboy/scp-action@master
      with:
          host: 35.233.168.216
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./allure-report/*"
          target: "report2"
    
    - name: Publish video
      uses: appleboy/scp-action@master
      with:
          host: 35.233.168.216
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./cypress/videos/base.js.mp4"
          target: "video"
    - name: Copy arttifact and Restart Server
      uses: appleboy/ssh-action@master
      with:
         host: 35.233.168.216
         username: ubuntu
         key: ${{ secrets.SSH_KEY }}
         port: 22
         script: ./refresh2.sh && ./video.sh
